import type { Engine } from './types';

export const DEFAULT_ENGINES: Engine[] = [
  {
    id: 'tech',
    name: 'Tech Builder',
    subtitle: 'Code, systems & side projects',
    color: '#3ecfcf',
    icon: '◈',
    structure: 'tower',
    activityLevel: 0.85,
    artifacts: [
      {
        id: 'art-1',
        title: 'TinyNet API',
        status: 'active',
        next: 'Write integration tests for /classify/ endpoint',
      },
    ],
  },
  {
    id: 'health',
    name: 'Health',
    subtitle: 'Fitness, sleep & nutrition',
    color: '#4dcc66',
    icon: '◎',
    structure: 'garden',
    activityLevel: 0.15,
    artifacts: [
      {
        id: 'art-2',
        title: 'Morning run habit',
        status: 'blocked',
        next: 'Start with 10 minutes, not 30',
      },
    ],
  },
  {
    id: 'finance',
    name: 'Finance',
    subtitle: 'Budgets, savings & investing',
    color: '#e6b233',
    icon: '⬡',
    structure: 'vault',
    activityLevel: 0.35,
    artifacts: [],
  },
  {
    id: 'creative',
    name: 'Creative',
    subtitle: 'Art, design & making things',
    color: '#cc4db3',
    icon: '◇',
    structure: 'workshop',
    activityLevel: 0.6,
    artifacts: [],
  },
  {
    id: 'learning',
    name: 'Learning',
    subtitle: 'Books, courses & deep dives',
    color: '#6680e6',
    icon: '⟁',
    structure: 'tower',
    activityLevel: 0.7,
    artifacts: [],
  },
  {
    id: 'writing',
    name: 'Writing',
    subtitle: 'Essays, docs & storytelling',
    color: '#e6993d',
    icon: '✦',
    structure: 'study',
    activityLevel: 0.25,
    artifacts: [],
  },
  {
    id: 'social',
    name: 'Social',
    subtitle: 'Relationships & community',
    color: '#e66666',
    icon: '△',
    structure: 'hall',
    activityLevel: 0.2,
    artifacts: [],
  },
  {
    id: 'music',
    name: 'Music',
    subtitle: 'Practice, theory & recording',
    color: '#80ccee',
    icon: '⊕',
    structure: 'chapel',
    activityLevel: 0.45,
    artifacts: [],
  },
];
